# Generated by Django 5.0.1 on 2024-01-23 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=50, verbose_name='название компании')),
                ('address', models.CharField(max_length=50, verbose_name='адрес компании')),
                ('phone', models.CharField(max_length=35, verbose_name='телефон')),
                ('email_company', models.EmailField(max_length=254, unique=True, verbose_name='почта компании')),
                ('partner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
