# Generated by Django 5.0.1 on 2024-01-24 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_client_options_alter_partner_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='дата создания')),
                ('periodicity', models.CharField(choices=[('0 0 * * *', 'раз в день'), ('0 0 * * 0', 'раз в неделю'), ('0 0 1 * *', 'раз в месяц')], max_length=50, verbose_name='периодичность')),
                ('status', models.CharField(max_length=50, verbose_name='статус')),
                ('clients_list', models.ManyToManyField(to='mailing.clientslist', verbose_name='список клиентов для рассылки')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.partner')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100, verbose_name='тема сообщения для рассылки')),
                ('text', models.CharField(max_length=100, verbose_name='текст сообщения для рассылки')),
                ('mailing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing')),
            ],
        ),
    ]
