# Generated by Django 5.0.1 on 2024-01-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_mailing_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='name_mailing',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='название рассылки'),
        ),
    ]
