# Generated by Django 5.0.1 on 2024-01-26 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_mailing_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_date', models.DateTimeField(auto_now=True, verbose_name='дата последней попытки')),
                ('status', models.CharField(max_length=20, verbose_name='статус попытки')),
                ('server_response', models.CharField(blank=True, max_length=200, null=True, verbose_name='ответ почтового сервера')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing')),
            ],
        ),
    ]
