# Generated by Django 5.0.1 on 2024-01-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_logmailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='periodicity',
            field=models.CharField(choices=[('*/1 * * * *', 'каждую минуту'), ('0 0 * * *', 'раз в день'), ('0 0 * * 0', 'раз в неделю'), ('0 0 1 * *', 'раз в месяц')], max_length=50, verbose_name='периодичность'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(verbose_name='текст сообщения для рассылки'),
        ),
    ]
