# Generated by Django 5.0.1 on 2024-01-28 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_partner_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('name_mailing',), 'permissions': [('can_blocked', 'can_blocked')], 'verbose_name': 'список клиентов для рассылки', 'verbose_name_plural': 'список клиентов для рассылки'},
        ),
    ]
