# Generated by Django 5.0.1 on 2024-01-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='заголовок')),
                ('content', models.TextField(verbose_name='Контент')),
                ('image', models.ImageField(upload_to='material/', verbose_name='изображение')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(default=0, verbose_name='кол-во просмотров')),
                ('date', models.DateTimeField(verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'блог',
                'verbose_name_plural': 'блог',
                'ordering': ('title',),
            },
        ),
    ]
