# Generated by Django 5.0.1 on 2024-01-18 13:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='имя')),
                ('surname', models.CharField(max_length=50, unique=True, verbose_name='фамилия')),
                ('age', models.IntegerField(verbose_name='возраст')),
                ('sex', models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=50, unique=True, verbose_name='пол')),
                ('city', models.CharField(max_length=50, unique=True, verbose_name='город')),
                ('description', models.CharField(max_length=500, verbose_name='описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='изображение')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'анкета',
            },
        ),
    ]
