# Generated by Django 5.0.1 on 2024-01-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='city',
            field=models.CharField(max_length=50, verbose_name='город'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='name',
            field=models.CharField(max_length=50, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='sex',
            field=models.CharField(choices=[('Мужчина', 'Мужчина'), ('Женщина', 'Женщина')], max_length=50, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='surname',
            field=models.CharField(max_length=50, verbose_name='фамилия'),
        ),
    ]
