# Generated by Django 5.0.1 on 2024-01-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_questionnaire_city_alter_questionnaire_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/media/', verbose_name='изображение'),
        ),
    ]
