# Generated by Django 5.0.1 on 2024-01-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_questionnaire_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='изображение'),
        ),
    ]
